import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hide-scrollbar flex flex-col`}
      >
        {/* Background Image */}
        <div className="absolute w-full h-full overflow-hidden" >
          <Image 
            src="/assets/Login.svg"
            alt="background"
            fill
            style={{ objectFit: "cover" ,display:"block" , maxInlineSize:'100%'}}
            priority
          />
        </div>

        {/* Content */}
        <div className="flex flex-row ml-auto h-full w-full">
          <div className="flex items-center justify-center flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
