import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import NavbarDynamic from "@/components/NavbarDynamic";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en" style={{ height: '100svh', minHeight: '100dvh' }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hide-scrollbar flex flex-col` }
        style={{ height: '100svh', minHeight: '100dvh' }}
      >
          <svg width="0" height="0"> 
          <defs>
            <clipPath id="cutout-rounded-px" clipPathUnits="userSpaceOnUse">
              <path d="
                M0 93
                Q0 65 28 65
                L37 65
                Q65 65 65 37
                L65 28
                Q65 0 93 0
                L1000 0
                L1000 1000
                L0 1000
              Z
              " />
     </clipPath>
   </defs>
</svg>    
          <Navbar/>
          {children}
      </body>
    </html>
  );
}
